convertOldPlayerData: true

#Auto moderator settings
autoModEnabled: true
autoModAlwaysEnabled: false
autoModKickReasonFly: "Remove your fly hack."
autoModKickReasonSpam: "Do not spam."
autoModKickReasonXray: "Remove your xray hack/texture pack."

#Detector settings
autoclickerDetectorEnabled: true
combatLogDetectorEnabled: true
factionBetrayalDetectorEnabled: true
flyDetectorEnabled: true
spamDetectorEnabled: true
xrayDetectorEnabled: true

#The following are items that won't be detected - needed for most guns to actually work
autoclickerAllowedWeapons:
- 290
- 291
- 292
- 293
- 294
- 340
autoclickerTimeBetweenAttacksInMillis: 500
combatLogWindowInSeconds: 10
combatLogFromMobs: false
combatLogFromPlayers: true
spamDetectorThresholdPerSecond: 5
xrayWarnOnDiamondRatio: 10
xrayWarnOnIronRatio: 0

#Cheat notification settings
jailAmountNoticeEnabled: true
jailsBeforeNotice: 2

#Blocked commands
blockedCommands:
- "op"

#Jail settings
allowedCommandsInJail:
- "jailstatus"
- "jailhelp"
- "rules"
- "help"
- "message"
- "t"
- "msg"
- "whisper"
- "r"
- "reply"