# SwornGuard Configuration

# Extra output to console
debug: false

# Auto moderator settings
autoModEnabled: true
autoModAlwaysEnabled: false
autoModKickReasonFly: "Remove your fly hack."
autoModKickReasonSpam: "Do not spam."
autoModKickReasonSpeed: "Remove your speed hack."
autoModKickReasonXray: "Remove your xray hack/texture pack."

# Detector settings
autoclickerDetectorEnabled: true
combatLogDetectorEnabled: true
factionBetrayalDetectorEnabled: true
flyDetectorEnabled: true
spamDetectorEnabled: true
speedDetectorEnabled: true
xrayDetectorEnabled: true

# AutoClicker settings
# The following are items that won't be detected - needed for most guns to actually work
autoclickerAllowedWeapons:
- 290
- 291
- 292
- 293
- 294
- 340

autoclickerTimeBetweenAttacksInMillis: 500

# Combat Logging
combatLogWindowInSeconds: 10
combatLogFromMobs: false
combatLogFromPlayers: true

# Fly Detector Settings
# These values are all for 1/4 second intervals.
flyDetectorSuspiciousVelocity: -2.0
flyDetectorSuspiciousDistFromGround: 7
flyDetectorSuspiciousMoveDist: 5

clipHackersWings: false

# Spam Detector Settings
spamDetectorMessageDecayTime: 2
spamDetectorThresholdPerSecond: 5

# Equivalent to the number of different checks the spam detector will perform to check if a message is spam. Value can be 0-4
spamDetectorComparisonLevel: 4

# Xray Detector Settings
xrayWarnOnDiamondRatio: 10
xrayWarnOnIronRatio: 0

# Cheat notification settings
jailAmountNoticeEnabled: true
jailsBeforeNotice: 2

# Blocked commands
blockedCommands:
- "op"

# Allowed Commands in jail
allowedCommandsInJail:
- "jailstatus"
- "jailhelp"
- "rules"
- "help"
- "message"
- "t"
- "msg"
- "whisper"
- "r"
- "reply"
- "f c"
- "f chat"

# Blocked Commands in hell
blockedCommandsInHell:
- "someCommand"

# AutoSave Task
autosave:
  enabled: true
  interval: 15
  # Delay in minutes between saves

# Join and Quit messages for patroling
joinMessage: "&e{0} joined the game."

quitMessage: "&e{0} left the game."

# Log Filters (regex)
log-filters:
- ^(.*)(/login)(.*)$
- ^(.*)(UUID of player)(.*)$
- ^(.*)(Loaded player file for)(.*)$
- ^(.*)(Removing player from memory)(.*)$
- ^(.*)(HTTP request failed)(.*)$
- ^(.*)(No response/invalid key)(.*)$