name: SwornGuard
main: net.t7seven7t.swornguard.SwornGuard
version: ${project.version} (Build ${project.build.number})
authors: [t7seven7t, dmulloy2]
softdepend: [SwornNations, Factions]
description: Comprehensive anti cheat plugin based around catching cheaters rather than preventing their actions.
commands:
    sg:
        description: Root command.
        aliases: [p, swornguard]
    patrol:
        description: Teleports the user to the next patrollable player.
        permission: swornguard.cmd.patrol
        usage: |
               /<command>
        aliases: [pat]
    autopatrol:
        description: Automatically teleports the user to the next patrollable player after given duration.
        permission: swornguard.cmd.autopatrol
        usage: |
               /<command>
               /<command> <time>
        aliases: [apat]
    vanish:
        description: Vanishes/Unvanishes the user.
        permission: swornguard.cmd.vanish
        usage: /<command>
               /<command> <on/off>
        aliases: [unvanish, hide, unhide]
    vanishlist:
        description: Displays a list of vanished users.
        permission: swornguard.cmd.vanishlist
        usage: /<command>
    ctp:
        description: Use to teleport to cheaters.
        permission: swornguard.cmd.cheatteleport
        usage: /<command>
    jail:
        description: Jails a player.
        permission: swornguard.cmd.jail
        usage: /<command> <player> <time> <reason>
    unjail:
        description: Unjails a player.
        permission: swornguard.cmd.unjail
        usage: /<command> <player>
    jailcheck:
        description: Checks a player's jail status.
        permission: swornguard.cmd.jailcheck
        usage: /<command> <player>
    jailreason:
        description: Modifies a player's jail reason.
        permission: swornguard.cmd.jailreason
        usage: /<command> <player> <reason>
    jailset:
        description: Set the region of the jail.
        permission: swornguard.cmd.jailset
        usage: |
                Usage:
                /<command>
                /<command> cancel
    jailstatus:
        description: Check your jail status.
        permission: swornguard.cmd.jailstatus
        usage: /<command>
    jailtime:
        description: Change jail time for a player.
        permission: swornguard.cmd.jailtime
        usage: /<command> <player> <time>
    jailhelp:
        description: Shows jail help.
        permission: swornguard.cmd.jailhelp
        usage: /<command>
    jailmute:
        description: Mute a jailed player.
        permission: swornguard.cmd.jailmute
    troll:
        description: Trololololololol
        usage: /<command> <player>
        aliases: [hell, trollhell]
    firework:
        description: Fireworks!
        usage: /<command>
    creepfun:
        description: Creepers riding bats with fireworks
        usage: /<command>
permissions:
    swornguard.admin:
        description: Gives access to all SwornGuard features.
        children:
            swornguard.moderator: true
            swornguard.canfly: true
            swornguard.allow.spam: true
            swornguard.allow.jailbuild: true
            swornguard.allow.blockedcommands: true
            swornguard.allow.usecommandsjailed: true
            swornguard.cmd.legit: true
            swornguard.cmd.ip: true
            swornguard.cmd.reload: true
            swornguard.cmd.jailset: true
            swornguard.cmd.unban: true
            swornguard.cmd.troll: true
            swornguard.allow.usecommandshell: true
            swornguard.firework: true
            swornguard.creepfun: true
            swornguard.troll.exempt: true
    swornguard.moderator:
        description: Gives access to features intended for moderators.
        children:
            swornguard.guard: true
            swornguard.cmd.vanish: true
            swornguard.cmd.vanishlist: true
            swornguard.cmd.patrol: true
            swornguard.cmd.ban: true
            swornguard.vanishspy: true
    swornguard.guard:
        description: Gives access to features intended for guards.
        children:
            swornguard.default: true
            swornguard.cmd.autopatrol: true
            swornguard.cmd.baninfo: true
            swornguard.cmd.jail: true
            swornguard.cmd.jailcheck: true
            swornguard.cmd.jailreason: true
            swornguard.cmd.jailtime: true
            swornguard.cmd.show: true
            swornguard.cmd.note: true
            swornguard.cmd.ratio: true
            swornguard.cmd.autopatrol: true
            swornguard.cmd.info.others: true
            swornguard.cmd.kick: true
            swornguard.cmd.unjail: true
            swornguard.cmd.cheatteleport: true
            swornguard.showcheatreports: true
            swornguard.trollspy: true
            swornguard.cmd.jailmute: true
    swornguard.default:
        description: Permissions for everyone
        children:
            swornguard.cmd.jailstatus: true
            swornguard.cmd.jailhelp: true
            swornguard.cmd.serverinfo: true
            swornguard.cmd.info: true
    swornguard.canfly:
        default: false
    swornguard.allow.spam:
        default: false
    swornguard.allow.jailbuild:
        default: false
    swornguard.allow.blockedcommands:
        default: false
    swornguard.allow.usecommandsjailed:
        default: false
    swornguard.cmd.legit:
        default: false
    swornguard.cmd.ip:
        default: false
    swornguard.cmd.reload:
        default: false
    swornguard.cmd.jailset:
        default: false
    swornguard.cmd.unban:
        default: false
    swornguard.cmd.vanish:
        default: false
    swornguard.cmd.vanishlist:
        default: false
    swornguard.cmd.patrol:
        default: false
    swornguard.cmd.ban:
        default: false
    swornguard.cmd.vanishspy:
        default: false
    swornguard.cmd.autopatrol:
        default: false
    swornguard.cmd.baninfo:
        default: false
    swornguard.cmd.jail:
        default: false
    swornguard.cmd.jailcheck:
        default: false
    swornguard.cmd.jailreason:
        default: false
    swornguard.cmd.jailtime:
        default: false
    swornguard.cmd.show:
        default: false
    swornguard.cmd.note:
        default: false
    swornguard.cmd.ratio:
        default: false
    swornguard.cmd.autopatrol:
        default: false
    swornguard.cmd.info.others:
        default: false
    swornguard.cmd.kick:
        default: false
    swornguard.cmd.unjail:
        default: false
    swornguard.cmd.cheatteleport:
        default: false
    swornguard.showcheatreports:
        default: false
    swornguard.cmd.jailstatus:
        default: true
    swornguard.cmd.jailhelp:
        default: true
    swornguard.cmd.serverinfo:
        default: true
    swornguard.cmd.info:
        default: true
    swornguard.cmd.jailmute:
        default: false
    swornguard.cmd.troll:
        default: false
    swornguard.allow.usecommandshell:
        default: false
    swornguard.trollspy:
        default: false
    swornguard.firework:
        default: false
    swornguard.creepfun:
        default: false
    swornguard.troll.exempt:
        default: false